[package]
name = "ValheimModloader"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.1", features = ["desktop"] }
reqwest = { version = "0.12.24", features = ["json"] }
rfd = "0.15.4"
serde = "1.0.228"
tokio = { version = "1.48.0", features = ["full"] }
zip = "6.0.0"

